export enum FonctionSalarie {

  COMMERCIAL = 'COMMERCIAL',
  ADMINISTRATIF = 'ADMINISTRATIF',
  DIRECTEUR = 'DIRECTEUR',
  DIRECTEUR_GENERAL = 'DIRECTEUR_GENERAL',
  RESPONSABLE = 'RESPONSABLE',
  MANAGER = 'MANAGER',
  TECHNICIEN = 'TECHNICIEN',
  INGENIEUR = 'INGENIEUR',
  CHAUFFEUR = 'CHAUFFEUR',
  AGENT = 'AGENT',
  AUTRE = 'AUTRE',
} 